// <auto-generated />
namespace DutyRoster.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Development010 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Development010));
        
        string IMigrationMetadata.Id
        {
            get { return "201801081616259_Development-0.1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
