// <auto-generated />
namespace DutyRoster.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Development011 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Development011));
        
        string IMigrationMetadata.Id
        {
            get { return "201801221748343_Development-0.1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
